// src/App.vue
<template>
  <div id="bossContainer">
    <settings
      v-if="settings.dialog"
      :tformat="settings.timeFormat"
      :calcMethod="settings.method"
      :lateAsr="settings.lateAsr"
      :localtime="localTime"
      :timezone="timezone"
      @update-parameters="updateSettings"
      @close-without-saving="settings.dialog = false"
    />
    <div id="secondBossContainer">
      <headerbox @show-dialog="settings.dialog = true" />
      <div class="contentBoxes">
        <timebox
          v-for="(val, i) in waqts"
          :key="i"
          :waqtName="val"
          :waqtTime="times[val.toLowerCase()]"
          :activeWaqt="nextWaqt === val"
          :timeToNextWaqt="timeToNextWaqt"
        />
      </div>
      <snackbar v-show="settings.snackbar" @reload="getLocation()" />
    </div>
  </div>
</template>

<script>
import Snackbar from '@/components/Snackbar.vue';
import Headerbox from '@/components/Headerbox.vue';
import Timebox from '@/components/Timebox.vue';
import Settings from '@/components/Settings.vue';
import { setInterval } from 'timers';
const moment = require('moment');
require('moment/locale/en-gb');

moment.locale('en-gb');

export default {
  components: {
    Snackbar,
    Headerbox,
    Timebox,
    Settings
  },
  data() {
    return {
      times: {
        fajr: '...',
        sunrise: '...',
        dhuhr: '...',
        asr: '...',
        maghrib: '...',
        isha: '...'
      },
      localTime: '...',
      timezone: '...',
      method: '...',
      settings: {
        city: '',
        country: '',
        timeFormat: 'h:mm A',
        method: 'karachi',
        lateAsr: true,
        snackbar: false,
        dialog: false,
        darkTheme: false, // ignore this
        loader: {
          loading: false
        }
      },
      nextWaqt: null,
      timeToNextWaqt: null,
      waqts: ['Fajr', 'Sunrise', 'Dhuhr', 'Asr', 'Maghrib', 'Isha']
    };
  },
  created() {
    if (localStorage.getItem('timeFormat') != null) {
      this.settings.timeFormat = localStorage.getItem('timeFormat');
      this.settings.method = localStorage.getItem('calcMethod');
      this.settings.lateAsr = localStorage.getItem('lateAsr') == 'true';
    } else {
      this.getLocation();
      this.settings.timeFormat = 'h:mm A';
      this.settings.method = this.determineCalcMethod();
      this.settings.lateAsr = true;
    }
    window.addEventListener('popstate', this.handleHistoryChange);
  },
  destroyed() {
    window.removeEventListener('popstate', this.handleHistoryChange);
  },
  beforeMount() {
    setInterval(this.getLocation(), 600000);
  },
  methods: {
    handleHistoryChange() {
      if (location.hash === '#settings') {
        this.settings.dialog = true;
      } else {
        this.settings.dialog = false;
      }
    },
    async getLocation() {
      var coords = {};
      await navigator.geolocation.getCurrentPosition(
        location => {
          coords.lat = location.coords.latitude.toFixed(4);
          coords.lon = location.coords.longitude.toFixed(4);
          this.getTimes(coords);
        },
        err => {
          console.log(err);
          console.log('Fallback to IP geolocation');
          this.$axios
            .get('https://api.ipgeolocationapi.com/geolocate')
            .then(response => {
              coords.lat = response.data.geo.latitude.toFixed(4);
              coords.lon = response.data.geo.longitude.toFixed(4);
              this.getTimes(coords);
            })
            .catch(error => {
              this.settings.snackbar = true;
              console.log(error);
            });
        }
      );
    },
    getTimes(coords) {
      const adhan = require('adhan');

      // Define the settings for adhan
      const coordinates = new adhan.Coordinates(coords.lat, coords.lon);
      const date = new Date();
      let params;
      const method = this.settings.method;
      switch (method) {
        case 'karachi':
          params = adhan.CalculationMethod.Karachi();
          break;
        case 'mwl':
          params = adhan.CalculationMethod.MuslimWorldLeague();
          break;
        case 'egypt':
          params = adhan.CalculationMethod.Egyptian();
          break;
        case 'makkah':
          params = adhan.CalculationMethod.UmmAlQura();
          break;
        case 'kuwait':
          params = adhan.CalculationMethod.Kuwait();
          break;
        case 'america':
          params = adhan.CalculationMethod.NorthAmerica();
          break;
      }
      // Asr method; Shafi has early Asrs, while Hanafi delays Asr time
      const lateAsr = this.settings.lateAsr;
      switch (lateAsr) {
        case true:
          params.madhab = adhan.Madhab.Hanafi;
          break;
        case false:
          params.madhab = adhan.Madhab.Shafi;
          break;
      }
      // For regions in higher latitudes
      params.highLatitudeRule = adhan.HighLatitudeRule.TwilightAngle;

      // Initialize
      const prayerTimes = new adhan.PrayerTimes(coordinates, date, params);

      let formattedTimes = {
        fajr: moment(prayerTimes.fajr).format(this.settings.timeFormat),
        sunrise: moment(prayerTimes.sunrise).format(this.settings.timeFormat),
        dhuhr: moment(prayerTimes.dhuhr).format(this.settings.timeFormat),
        asr: moment(prayerTimes.asr).format(this.settings.timeFormat),
        maghrib: moment(prayerTimes.maghrib).format(this.settings.timeFormat),
        isha: moment(prayerTimes.isha).format(this.settings.timeFormat)
      };

      // Set data
      this.times = formattedTimes;
      this.localTime = moment().format('MMMM Do YYYY');
      this.timezone =
        'GMT' +
        moment()
          .parseZone()
          .format('Z');
      const { nextWaqt, timeToNextWaqt } = this.determineNextWaqt(formattedTimes);
      this.nextWaqt = nextWaqt;
      this.timeToNextWaqt = timeToNextWaqt;

      // Hide snackbar on success
      this.settings.snackbar = false;
    },
    determineNextWaqt(formattedTimes) {
      const unixNow = moment().unix();

      const unixFajr = moment(formattedTimes.fajr, this.settings.timeFormat).unix();
      const unixSunrise = moment(formattedTimes.sunrise, this.settings.timeFormat).unix();
      const unixDhuhr = moment(formattedTimes.dhuhr, this.settings.timeFormat).unix();
      const unixAsr = moment(formattedTimes.asr, this.settings.timeFormat).unix();
      const unixMaghrib = moment(formattedTimes.maghrib, this.settings.timeFormat).unix();
      const unixIsha = moment(formattedTimes.isha, this.settings.timeFormat).unix();

      let nextWaqt;
      let timeToNextWaqt;

      if (unixNow < unixFajr) {
        nextWaqt = 'Fajr';
        timeToNextWaqt = moment.unix(unixFajr).fromNow();
      } else if (unixNow < unixSunrise && unixNow > unixFajr) {
        nextWaqt = 'Sunrise';
        timeToNextWaqt = moment.unix(unixSunrise).fromNow();
      } else if (unixNow < unixDhuhr && unixNow > unixSunrise) {
        nextWaqt = 'Dhuhr';
        timeToNextWaqt = moment.unix(unixDhuhr).fromNow();
      } else if (unixNow < unixAsr && unixNow > unixDhuhr) {
        nextWaqt = 'Asr';
        timeToNextWaqt = moment.unix(unixAsr).fromNow();
      } else if (unixNow < unixMaghrib && unixNow > unixAsr) {
        nextWaqt = 'Maghrib';
        timeToNextWaqt = moment.unix(unixMaghrib).fromNow();
      } else if (unixNow < unixIsha && unixNow > unixMaghrib) {
        nextWaqt = 'Isha';
        timeToNextWaqt = moment.unix(unixIsha).fromNow();
      } else if (unixNow > unixIsha) {
        nextWaqt = 'Fajr';
        timeToNextWaqt = 'tomorrow';
      }

      return {
        nextWaqt,
        timeToNextWaqt
      };
    },
    /** Determines calculation method coarsely from timezone */
    determineCalcMethod() {
      const timeZone = parseInt(
        moment()
          .parseZone()
          .format('Z')
      );
      if (timeZone >= 0 && timeZone <= 2) {
        return 'mwl';
      } else if (timeZone >= 3 && timeZone <= 4) {
        return 'makkah';
      } else if (timeZone >= 5 && timeZone <= 7) {
        return 'karachi';
      } else if (timeZone >= 8 && timeZone <= 12) {
        return 'mwl';
      } else {
        return 'mwl';
      }
    },
    updateSettings(parameters) {
      this.settings.timeFormat = parameters.timeFormat;
      this.settings.method = parameters.calcMethod;
      this.settings.lateAsr = parameters.lateAsr;
      this.settings.dialog = false;
      this.getLocation();
      localStorage.setItem('timeFormat', parameters.timeFormat);
      localStorage.setItem('calcMethod', parameters.calcMethod);
      localStorage.setItem('lateAsr', parameters.lateAsr);
      // location.reload();
    }
  },
  watch: {
    'settings.dialog': function(val) {
      if (val === true) {
        location.hash = 'settings';
      } else {
        location.hash = '';
      }
    }
  }
};
</script>

<style lang="scss">
@import './styles/base';

.contentBoxes {
  display: grid;
  grid-template-columns: repeat(3, 33.3%);
  grid-template-rows: repeat(2, 210px);
}

@media (max-width: 800px) {
  .contentBoxes {
    grid-template-columns: repeat(2, 50%);
    grid-template-rows: repeat(3, 210px);
  }
}
@media (max-width: 575px) {
  .contentBoxes {
    grid-template-columns: 100%;
    grid-template-rows: repeat(6, 210px);
  }
  #headerBox {
    margin: 30px 50px 10px 50px;
    display: block;
  }
  #headerText {
    text-align: center;
  }
}

@media (min-width: 825px) {
  #secondBossContainer {
    padding: 3% 5%;
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    width: 80%;
  }
}
</style>

// src/App.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { PrayerTimes, Prayer, CalculationMethod } from 'adhan';
  import { formatDistanceStrict } from 'date-fns';
  import { timesStore, settingsStore } from './store/store';
  import { fade } from 'svelte/transition';
  import Snackbar from './components/Snackbar.svelte';
  import Headerbox from './components/Headerbox.svelte';
  import Timebox from './components/Timebox.svelte';
  import SettingsDialog from './components/Settings.svelte';
  import getCurrentPosition from './getCurrentPosition';

  const prayers = ['Fajr', 'Sunrise', 'Dhuhr', 'Asr', 'Maghrib', 'Isha'];

  let times: Nullable<Prayers> | null = null;
  let settings: Settings | null = null;
  let localTime: Date = new Date();
  let timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;

  let nextPrayer: Prayer | null = null;
  let timeToNextPrayer: string | null = null;
  let snackbar = false;
  let dialog = false;
  let error: string | null = null;
  const interval = setInterval(() => init(), 60 * 1000);

  const unsubscribeTimesStore = timesStore.subscribe(
    (value) => (times = value)
  );
  const unsubscribeSettingsStore = settingsStore.subscribe(
    (v) => (settings = v)
  );

  function setError(e: any) {
    console.error(e);
    error = e.message;
    snackbar = true;
  }

  onMount(() => {
    if (localStorage.getItem('timeFormat') != null) {
      settingsStore.update((v) => ({
        colorScheme: localStorage.getItem('colorScheme') as ColorScheme,
        timeFormat: localStorage.getItem('timeFormat')!,
        calcMethod: localStorage.getItem('calcMethod')! as CalcMethod,
        latitude: Number(localStorage.getItem('latitude')!),
        longitude: Number(localStorage.getItem('longitude')!),
      }));
      init();
    } else {
      getCurrentPosition()
        .then(([latitude, longitude]) => {
          settingsStore.update((s) => ({
            ...s,
            calcMethod: determineCalcMethod(),
            timeFormat: 'h:mm a',
            latitude,
            longitude,
          }));
        })
        .then(() => {
          init();
        })
        .catch(setError);
    }
  });

  onDestroy(() => {
    unsubscribeSettingsStore();
    unsubscribeTimesStore();
    clearInterval(interval);
  });

  function saveToStorage() {
    localStorage.setItem('timeFormat', settings.timeFormat);
    localStorage.setItem('calcMethod', settings.calcMethod);
    localStorage.setItem('latitude', settings.latitude.toString());
    localStorage.setItem('longitude', settings.longitude.toString());
    localStorage.setItem('colorScheme', settings.colorScheme);
  }

  async function init() {
    snackbar = false;
    setColorScheme();
    setTimes().catch(setError);
  }

  function setColorScheme() {
    switch (settings.colorScheme) {
      case 'default':
        document.body.className = '';
        break;
      case 'dark':
        document.body.className = 'dark';
        break;
      case 'light':
        document.body.className = 'light';
        break;
    }
  }

  async function setTimes() {
    localTime = new Date();

    if (settings == null) {
      throw new Error('Settings were never initialized');
    }

    const { latitude, longitude } = settings;

    if (latitude == null || longitude == null) {
      throw new Error('Location is not set');
    }

    // Define the settings for adhan
    const prayerTimes = new PrayerTimes(
      { latitude, longitude },
      new Date(),
      mapStringToParams(settings.calcMethod)
    );
    const { fajr, sunrise, dhuhr, asr, maghrib, isha } = prayerTimes;
    timesStore.set({ fajr, sunrise, dhuhr, asr, maghrib, isha });

    // Set data
    nextPrayer = prayerTimes.nextPrayer();
    if (nextPrayer != null && nextPrayer !== Prayer.None) {
      timeToNextPrayer = formatDistanceStrict(
        prayerTimes.timeForPrayer(nextPrayer),
        localTime,
        {
          addSuffix: true,
          roundingMethod: 'round',
        }
      );
    }
  }

  function mapStringToParams(method: CalcMethod): adhan.CalculationParameters {
    switch (method) {
      case 'karachi':
        return CalculationMethod.Karachi();
      case 'mwl':
        return CalculationMethod.MuslimWorldLeague();
      case 'egypt':
        return CalculationMethod.Egyptian();
      case 'makkah':
        return CalculationMethod.UmmAlQura();
      case 'kuwait':
        return CalculationMethod.Kuwait();
      case 'isna':
        return CalculationMethod.NorthAmerica();
      case 'singapore':
        return CalculationMethod.Singapore();
      case 'turkey':
        return CalculationMethod.Turkey();
      case 'mcw':
        return CalculationMethod.MoonsightingCommittee();
      default:
        throw new Error('Unsupported calculation method');
    }
  }

  function prayerEnumToString(prayer: Prayer) {
    switch (prayer) {
      case Prayer.Fajr:
        return 'Fajr';
      case Prayer.Dhuhr:
        return 'Dhuhr';
      case Prayer.Asr:
        return 'Asr';
      case Prayer.Maghrib:
        return 'Maghrib';
      case Prayer.Isha:
        return 'Isha';
      case Prayer.Sunrise:
        return 'Sunrise';
      default:
        return null;
    }
  }

  /** Coarse approximation of method from timezone */
  function determineCalcMethod(): CalcMethod {
    const timeZone = -(localTime.getTimezoneOffset() / 60);
    if (timeZone >= 0 && timeZone <= 2) {
      return 'mwl';
    } else if (timeZone >= 3 && timeZone <= 4) {
      return 'makkah';
    } else if (timeZone >= 5 && timeZone <= 7) {
      return 'karachi';
    } else if (timeZone >= 8 && timeZone <= 12) {
      return 'mwl';
    } else if (timeZone <= -5 && timeZone >= -9) {
      return 'mcw';
    } else {
      return 'mwl';
    }
  }
</script>

{#if dialog}
  <SettingsDialog
    {localTime}
    {timeZone}
    onClose={() => {
      dialog = false;
      init();
      saveToStorage();
    }}
  />
{/if}

<div id="boss-container">
  <Headerbox onClick={() => (dialog = true)} />
  {#if times != null}
    <div class="content-boxes">
      {#each prayers as prayer}
        <Timebox
          prayerName={prayer}
          prayerTime={times[prayer.toLowerCase()]}
          isNextPrayer={prayerEnumToString(nextPrayer) === prayer}
          {timeToNextPrayer}
        />
      {/each}
    </div>
  {/if}
</div>

{#if snackbar && error != null}
  <Snackbar onReload={() => init()} message={error} />
{/if}

<style lang="scss">
  .content-boxes {
    display: grid;
    grid-template-columns: repeat(3, 33.3%);
    grid-template-rows: repeat(2, 210px);
  }

  @media (max-width: 800px) {
    .content-boxes {
      grid-template-columns: repeat(2, 50%);
      grid-template-rows: repeat(3, 210px);
    }
  }
  @media (max-width: 575px) {
    .content-boxes {
      grid-template-columns: 100%;
      grid-template-rows: repeat(6, 210px);
    }
    // #header-box {
    //   margin: 30px 50px 10px 50px;
    //   display: block;
    // }
    // #header-text {
    //   text-align: center;
    // }
  }

  @media (min-width: 825px) {
    #boss-container {
      padding: 3% 5%;
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      width: 80%;
    }
  }
</style>
